language: cpp

solution: ./TechPlayers-master\win32\TechPlayers_Win32_2011.sln

install:
	- sudo apt-get install nunit-console
	- nunget restore ./TechPlayers-master\win32\TechPlayers_Win32_2011.sln

script:
	- xbuild ./TechPlayers-master\win32\TechPlayers_Win32_2011.sln

branches:
  only:
    - master
    - 1.8.7
    - 2.2
    - /^v\d+\./

notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#rubinius"
    template:
      - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/9502afd22ca6c8e85fb3
    on_success: change
    on_failure: always
    on_start: always

env:
  - RVM=2.0.0 LANG="en_US.UTF-8"
