language: cpp

compiler:
  - gcc
  - clang


before_script:
  - travis_retry bundle
  - if [ $TRAVIS_OS_NAME == linux ]; then travis_retry ./configure --llvm-config llvm-config-3.4; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then travis_retry ./configure; fi

env:
  - RVM=2.0.0 LANG="en_US.UTF-8"

os:
  - linux
  - osx