
language: cpp

before_script:
  - cd TechPlayers-master
  - mkdir lib
  - pwd
  - ls
  - sh ./configure
  - make
  - make-check
  - make install DESTDIR=~/kiranbarnana/TechPlayers/TechPlayers-master/lib/
  - make clean

script: . ./autogen.sh
