
language: cpp

before_script:
  - cd TechPlayers-master
  - mkdir lib

script: . ./autogen.sh

after-script: . ./run_tests.sh
deploy:
  edge: true
  provider: cloudfoundry
  username: hydsri.kiran@gmail.com
  password: asdf1234
  api: https://api.run.pivotal.io
  organization: VERIZON
  space: staging